Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -105,3 +105,54 @@ jobs:
           files: ${{ steps.apk.outputs.files }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      # ========== 发布Gitee Release（使用MY_GITEE_TOKEN） ==========
+      - name: 同步Tag并发布Gitee Release
+        if: success() && github.event.inputs.publishGitee == 'true'
+        env:
+          MY_GITEE_TOKEN: ${{ secrets.MY_GITEE_TOKEN }}
+          GITEE_REPO: cyh92/legado
+          TAG_NAME: ${{ steps.date.outputs.version }}
+          RELEASE_TITLE: legado_app_${{ steps.date.outputs.version }}
+          APK_DIR: ${{ steps.apk.outputs.files }}
+          TARGET_BRANCH: ${{ github.event.inputs.defaultBranch }}
+        run: |
+          # 2. 创建Gitee Release
+          NOTE_FILE="${{ github.workspace }}/legado/release-notes.md"
+          if [[ ! -f "$NOTE_FILE" ]]; then
+            echo "ERROR: 发布日志文件不存在 $NOTE_FILE"
+            exit 1
+          fi
+          # 读取日志并转义双引号
+          RELEASE_NOTE_CONTENT=$(cat "$NOTE_FILE" | sed 's/"/\\"/g')
+          
+          API_URL="https://gitee.com/api/v5/repos/cyh92/legado/releases"
+          BODY="自动构建发布版本 ${TAG_NAME}
+          构建分支：${TARGET_BRANCH}
+          ${RELEASE_NOTE_CONTENT}"
+          
+          #CREATE_RES=$(curl -X POST --header 'Content-Type: application/json;charset=UTF-8' '${API_URL}' -d '{"access_token":"${{ secrets.MY_GITEE_TOKEN }}","tag_name":"${TAG_NAME}","name":"${RELEASE_TITLE}","body":"${BODY}","target_commitish":"${TARGET_BRANCH}"}')
+          CREATE_RES=$(curl -X POST -H "Content-Type: application/json;charset=UTF-8" "${API_URL}" -d "{\"access_token\":\"${{ secrets.MY_GITEE_TOKEN }}\",\"tag_name\":\"${TAG_NAME}\",\"name\":\"${RELEASE_TITLE}\",\"body\":\"${BODY}\",\"target_commitish\":\"${TARGET_BRANCH}\"}")
+          # 提取release id
+          RELEASE_ID=$(echo "$CREATE_RES" | jq -r '.id')
+          if [[ "$RELEASE_ID" == "null" || -z "$RELEASE_ID" ]]; then
+            echo "创建Gitee Release失败，返回：$CREATE_RES"
+            exit 1
+          fi
+          echo "Gitee Release 创建成功 ID: $RELEASE_ID"
+
+          # 3. 上传所有APK附件
+          for apk in ${APK_DIR}/*.apk; do
+            if [ -f "$apk" ]; then
+              echo "正在上传附件: $apk"             
+              curl -s -X POST \
+              -F "access_token=${MY_GITEE_TOKEN}" \
+              -F "owner=cyh92" \
+              -F "repo=legado" \
+              -F "release_id=${RELEASE_ID}" \
+              -F "file=@$apk" \
+              "$API_URL/${RELEASE_ID}/attach_files"
+            echo "上传完成：$apk"
+            fi
+          done
+          echo "所有APK附件上传完成"
